repository:
  description: DNS Configuration
  private: false
  has_issues: false
  has_pull_requests: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
